shop_app/urls.py
from django.urls import path
from django.conf.urls import url
from shop_app import views
from .views import addToCart, myCart, removeFromCart, checkout, newOrder, myOrders
app_name="shop_app"

urlpatterns=[
    path('',views.Index.as_view(),name='index'),
    path('register/',views.Register,name="register"),
    path('login/',views.User_login,name="userLogin"),
    path('logout/',views.user_logout,name="userLogout"),
    path('Aboutus/',views.Aboutus.as_view(),name="aboutus"),
    path('stock/list/',views.Stocklist.as_view(),name="StockList"),
    url(r'(?P<pk>\d+)/',views.Stockdetail.as_view(),name="StockDetail"),
    path('stock/new/',views.Createstock.as_view(),name="StockCreate"),
    path(r'update/(?P<pk>\d+)/',views.StockUpdateView.as_view(),name="update"),
    path(r'delete/(?P<pk>\d+)/',views.StockDeleteView.as_view(),name="delete"),
    path('search/',views.SearchResultView.as_view(),name="SearchData"),
    path(r'addToCart/<int:pk>', addToCart, name="addToCart"),
    path(r'myCart', myCart, name="myCart"),
    path(r'removeFromCart/<int:pk>', removeFromCart, name="removeFromCart"),
    path(r'checkout/<int:pk>', checkout, name="checkout"),
    path(r'newOrder/<int:pk>', newOrder, name="newOrder"),
    path(r'myOrders', myOrders, name="myOrders"),

]

shop_pro/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('lucifer_is_here_babe/', admin.site.urls),
    path('',include('shop_app.urls'))
]

shop_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.core.validators import MaxValueValidator
from datetime import datetime
from django.utils.timezone import now

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    # extra fields
    ShopName=models.CharField(max_length=100)

    def __str__(self):
        return self.ShopName
class Medicine(models.Model):
    Shop=models.ForeignKey(Profile,related_name="medicines",on_delete=models.CASCADE)
    Name=models.CharField(max_length=100)
    Salt=models.CharField(max_length=100,blank= True,null=True)
    Company=models.CharField(max_length=100,blank= True,null=True)
    MRP=models.PositiveIntegerField()
    MFD = models.CharField(max_length=20)
    Expiry = models.CharField(max_length=20)
    Publish_date=models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.Name
    def get_absolute_url(self):
        return reverse("shop_app:StockDetail",kwargs={'pk':self.pk})


class Cart(models.Model):
    user = models.ForeignKey("Profile", on_delete=models.CASCADE)
    medicine = models.ForeignKey("Medicine", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

class Orders(models.Model):
    user = models.ForeignKey("Profile", on_delete=models.CASCADE)
    medicine = models.ForeignKey("Medicine", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    time = models.DateTimeField(default=now)

shop_app/forms.py
from django import forms
from django.contrib.auth.models import User
from shop_app.models import Profile

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','password','email')
class ProfileForm(forms.ModelForm):
    class Meta():
        model=Profile
        fields=('ShopName',)

shop_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView , CreateView , UpdateView , DetailView ,ListView, DeleteView
from django.http import HttpResponse
from shop_app.forms import ProfileForm,UserForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate , login , logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from shop_app.models import  Profile,Medicine,Cart, Orders
from django.urls import reverse_lazy
from django.utils import timezone
from django.db.models import Q
from django.core.mail import send_mail
from django.conf import settings


# Create your views here.
class Index(TemplateView):
    template_name='shop_app/index.html'

class Aboutus(TemplateView):
    template_name='shop_app/AboutUs.html'



def Register(request):
    Registered=False
    if request.method=='POST':
        profile_form=ProfileForm(request.POST)
        user_form=UserForm(request.POST)
        if profile_form.is_valid() and user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile=profile_form.save(commit=False)
            profile.user=user
            profile.save()
            Registered=True
        else:
            return HttpResponse('Invalid Login Id or Password')
    else:
        profile_form=ProfileForm
        user_form=UserForm
    return render(request,'shop_app/registration.html',{'Registered':Registered,'profile_form':profile_form,'user_form':user_form})

def User_login(request):
    if request.method=='POST':
        user_name=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=user_name,password=password)
        if user:
            if user.is_active:
                print(user.id)
                request.session['id'] = user.id
                login(request,user)
                return redirect('shop_app:index')
                print('successfull')
            else:
                return HttpResponse('INVALID USERNAME OR PASSWORD')
        else:
            return HttpResponse('Invalid Login')
            print("SORRY WE CAN'T LET YOU LOG IN")
    else:
        return render(request,'shop_app/login.html',{})

@login_required
def user_logout(request):
    logout(request)
    return redirect('shop_app:index')
class Stocklist(LoginRequiredMixin,ListView):
    model=Medicine
    context_object_name="stock_list"
    template_name="shop_app/medicine_list.html"



class Stockdetail(LoginRequiredMixin,DetailView):
    model=Medicine
    context_object_name="stock_detail"
    template_name='shop_app/medicine_detail.html'

class Createstock(LoginRequiredMixin,CreateView):
    model=Medicine
    fields=('Shop','Name','Salt','Company','MRP','MFD','Expiry')
    login_url='/login/'
    redirect_field_name="shop_app/medicine_detail.html"


class StockUpdateView(LoginRequiredMixin,UpdateView):
    model=Medicine
    fields=('Shop','Name','Salt','Company','MRP','MFD','Expiry')
    template_name="shop_app/medicine_form.html"
    login_url='/login/'
    redirect_field_name="shop_app/medicine_detail.html"


class StockDeleteView(LoginRequiredMixin,DeleteView):
    model=Medicine
    success_url=reverse_lazy("shop_app:StockList")
    template_name="shop_app/medicine_confirm_delete.html"
    login_url='/login/'
    redirect_field_name="shop_app/medicine_detail.html"


class SearchResultView(ListView):
    model=Medicine
    template_name="shop_app/Searchpage.html"
    def get_queryset(self):
        query=self.request.GET.get('q')
        object_list= Medicine.objects.filter(
         Q(Name__icontains=query) | Q(Salt__icontains=query) | Q(MFD__icontains=query) | Q(Expiry__icontains=query)
        )
        return object_list

def addToCart(request, pk):
    u = User.objects.get(id=request.session['id'])
    p = Profile.objects.get(user=u)
    m = Medicine.objects.get(id=pk)
    if Cart.objects.filter(user=p, medicine=m).exists():
        i = Cart.objects.get(user=p, medicine=m)
        c = i.quantity + 1
        i.quantity = c
        i.save()
    else:
        item = Cart.objects.create(user=p, medicine=m)
        item.save()
    return redirect('/stock/list/')

def myCart(request):
    u = User.objects.get(id=request.session['id'])
    p = Profile.objects.get(user=u)
    items = Cart.objects.filter(user=p)
    return render(request, 'shop_app/myCart.html', {'items':items})

def removeFromCart(request, pk):
    item = Cart.objects.get(id=pk)
    c = item.quantity - 1
    if c == 0:
        item.delete()
    else:
        item.quantity = c
        item.save()
    return redirect('/myCart')

def checkout(request, pk):
    items = Cart.objects.filter(id=pk)
    return render(request, 'shop_app/checkout.html', {'items':items})

def  newOrder(request, pk):
    item = Cart.objects.get(id=pk)
    o = Orders.objects.create(user=item.user, medicine=item.medicine, quantity=item.quantity)
    o.save()

    subject = 'ORDER CONFIRMATION'
    message = 'Your order of \n Product : '+ item.medicine.Name + '\n Price : '+ str(item.medicine.MRP) + '\n is confirmed'
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [item.user.user.email,]
    send_mail( subject, message, email_from, recipient_list )

    return render(request, 'shop_app/confirm.html')


def myOrders(request):
    u = User.objects.get(id=request.session['id'])
    p = Profile.objects.get(user=u)
    items = Orders.objects.filter(user=p).order_by('-time')
    return render(request, "shop_app/myOrders.html", {'items':items})

shop_app/templates/shop_app/AboutUs.html
{% extends 'shop_app/base.html' %}
{% block sample %}
<div class="bg">
<h1 id="well"> About Us</h1>
<div class="shiv container">
<h2>Trying to make diffrence and ease in billing and managing medicines stock for the chemists shops.
<br><br>
Medicines management is an evidence-based approach to prescribing which balances the safety, tolerability, effectiveness, cost and simplicity of treatments. Good medicines management means that patients receive better, safer and more convenient care.

Medicines management includes:

Giving unbiased information about medicines and treatments
Supporting practitioners and patients to make best use of medicines
Minimising the harm caused by medicines
Developing local guidelines to optimise the management of conditions
Communicating with local hospital trusts
<hr>
<hr>
Hope you are enjoying using our services and in futur also we wish we can give you alot of new features ,<br>but for that , it will take some time , but not so long.
<br>
</h2>
</div>
<!-- Footer -->
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
        <a color="#E41F09" class="btn btn-outline-white" href="#" target="_blank" role="button">9860311717 
            <i class="fas fa-phone"></i>
        </a>
        <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">MedicineBook.com
            <i class="fa fa-envelope" aria-hidden="true"></i>
        </a>


    <!--Copyright-->
    <div class="footer-copyright py-3" color="white">
        © 2018 Copyright:
        <a href="https://mail.google.com/mail/u/0/#inbox" target="_blank"> MedicineBook@gmail.com </a>
    </div>
    <!--/.Copyright-->

</div>
{% endblock %}

shop_app/templates/shop_app/Searchpage.html
{% extends 'shop_app/base.html' %}
{% block sample %}
<br><br>
<h1 class="qrt">Search Results</h1>
<br><br><br>
<div class="jumbotron container">
{% for med in object_list %}
  <div class="alert alert-dark" role="alert">
    <p><a class=" bad" href="{{med.id}}">{{med.Name}}</a></p>
    <p>Salt: {{med.Salt}}</p>
    <p>MFD: {{med.MFD}}</p>
    <p>Expiry: {{med.Expiry}}</p>
  </div>
 <hr>
 {% endfor %}
</div>




{% endblock %}

shop_app/templates/shop_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- bootstarp code -->

<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- google fonts code -->
<link href="https://fonts.googleapis.com/css?family=Amatic+SC|Cutive+Mono|Dancing+Script|Mali|Open+Sans+Condensed:300|Shadows+Into+Light&display=swap" rel="stylesheet">

{% comment %} css linking {% endcomment %}

 <link rel="stylesheet" href="{% static 'css/sample.css' %}"/>
<style type="text/css">
  /*footer styling */
  .page-footer {
        background-color: #17171b;
    }
    .pt-4{
      font-style: verdana;
      text-decoration-color: white;
    }
      .bg {
  /* The image used */
  background-image: url("jj.jpg");

  /* Full height */
  height: 100%; 

  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
</style>
  </head>
  <body>
    <!-- navbar code starts -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a  class="navbar-brand " href="{% url 'shop_app:index' %}">MedicineBook</a>
      <a class="nav-item nav-link" href="{% url 'shop_app:index' %}">Home</a>
      <a class="nav-item nav-link" href="{% url 'shop_app:aboutus' %}">About Us</a>
      {% if user.is_authenticated %}

      <a class="nav-item nav-link" href="{% url 'shop_app:StockCreate' %}">Create Stock</a>
      <a class="nav-item nav-link" href="{% url 'shop_app:StockList' %}">Stock List</a>
      <a class="nav-item nav-link" href="{% url 'shop_app:myOrders' %}">My Orders</a>
      <a class="nav-item nav-link" href="{% url 'shop_app:userLogout' %}">Logout</a>


      {% else %}
      <a class="nav-item nav-link" href="{% url 'shop_app:userLogin' %}">Login</a>
      {% endif %}

    </div>
  </div>
</nav>

    <!-- navbar code ends -->

 <!-- block code start -->
 {% block sample %}
 {% endblock %}
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

shop_app/templates/shop_app/checkout.html
{% extends 'shop_app/base.html' %}
{% block sample %}
<div class="soc">
    <h3> <center> Medicines List </center> </h3>
</div>

<br>
  <div class="card" style="margin-left:33%; width:33%;">
  
    {% for item in items %}
      <form class="form-group" method="POST">   {% csrf_token %}
        Product : <input type="text" class="form-control" value="{{item.medicine.Name}}" readonly>
        Price : <input type="text" class="form-control" value="{{item.medicine.MRP}}" readonly>
        Quantity : <input type="text" class="form-control" value="{{item.quantity}}" readonly> <br>
        <a class="form-control btn btn-success" style="max-width:20%; margin-left:40%;" href="{% url 'shop_app:newOrder' pk=item.pk %}"> Confirm Order </a>
      </form>
      {% endfor %}
   </div>

{% endblock %}

shop_app/templates/shop_app/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Success</title>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'register/style.css' %}">
	<meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" rel="stylesheet">
</head>
<style>
tr {
    text-align: center;
}
a {
    color: black;
}
th {
    color:black;
    font: bolder;
    text-align: center;
}
div.footer {
    display: inline-block;
    margin-left: 150px;
}
body {
    background-image: url("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjTrMnbHu1UYIWhCUo8GSCEc46tvJ9rkkSojyurQkFSOAeH6gclA&s");
    background-repeat: no-repeat;
    background-size: cover;
}

</style>


<body>
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-8">
				<div class="alert alert-success" role="alert'">
					<h4 class="alert-heading">Success</h4>
						<p><strong> Order Confirmation has been sent to your email !!!  </strong></p>
                        <a class ="btn btn-primary" href="/"> HOME </a>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

shop_app/templates/shop_app/index.html
{% extends 'shop_app/base.html' %}
{% load staticfiles %}
{% block sample %}

<!-- carousel code starts / slideshow code starts -->
<div class="slide">
  <div class="bd-example">
  <div id="carouselExampleCaptions" class="carousel slide"  data-ride="carousel">
     <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="i1" src="{% static 'images/j2.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block www ">
          <h5 class="www">Manage your Medicines Stock Details</h5>
          <p class="www">Easily add , update or remove the medicines data in your accordance.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img class="i2" src="{% static 'images/med.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block www">
          <h5 class="www">Flexible Database</h5>
          <p class="www">We are providing you a Flexible Data Base for storage.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img class="i3" src="{% static 'images/i1.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block  www">
          <h5 class="www">Great User Experience</h5>
          <p class="www">Due to simple and easy working GUI we are proving ease to users in usage</p>
        </div>
     </div>

    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
   </a>

  </div>
</div>
</div>


<!-- carousel code ends / slideshow code ends -->

<div class="fh">
<h1>Welcome to <br> <span id='first_head'>Medicines Data management</span> </h1>
</div>

<div class="cards  container">

  <div class="card" style="width: 18rem;">
    <img src="{%  static 'images/i4.jpg'%}" class="card-img-top" alt="..."/>
    <div class="card-body">
      <p class="card-text">Having Problems in Medicines managing bills and their minor details?</p>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    <img src="{%  static 'images/i5.jpg'%}" class="card-img-top" alt="..."/>
    <div class="card-body">
      <p class="card-text">Finding it a Hassle to maintain all these medicines details ?</p>
    </div>
  </div>


  <div class="card" style="width: 18rem;">
    <img src="{%  static 'images/i6.jpg'%}" class="card-img-top" alt="..."/>
    <div class="card-body">
      <p class="card-text">Piles of Expired Medicines are found when checked properly ?</p>
    </div>
  </div>

</div>

<div class="content">
  <h4>As In Our daily routine we face problems like managing the medicines  stock details , like Batch Number , Manufactering Date and other information ,  which results to the wastage of medicines whoes expiry date is near and also have to face <br> a great hassle while making bills for further use
  but  not to worry because now , with the help of our Medicine Management Web App.</h4>
</div>


<div class="get" >
  <a class="getty" href="{% url 'shop_app:register' %}" >  <button  type="button" class="btn btn-secondary btn-lg btn-block btn btn-dark ">Get Started</button></a>


<!-- Footer -->
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
        <a color="#E41F09" class="btn btn-outline-white" href="#" target="_blank" role="button">9860311717 
            <i class="fas fa-phone"></i>
        </a>
        <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">MedicineBook.com
            <i class="fa fa-envelope" aria-hidden="true"></i>
        </a>


    <!--Copyright-->
    <div class="footer-copyright py-3" color="white">
        © 2018 Copyright:
        <a href="https://mail.google.com/mail/u/0/#inbox" target="_blank"> MedicineBook@gmail.com </a>
    </div>
    <!--/.Copyright-->

{% endblock %}

shop_app/templates/shop_app/login.html
{% extends 'shop_app/base.html' %}


{% block sample %}

<div class="qwe">
  <h3 >Login Here</h3>
</div>
<br><br>
<div class="jumbotron container">
<form  action="{% url 'shop_app:userLogin' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    
    <label for="username">Username :</label>
    
    <input class="form-control" type="text" name="username" placeholder="Enter your Username" >
    <label for="password">Password :</label>
    <input class="form-control" type="password" name="password" placeholder="Enter your password">
    <br>
    <input class='btn btn-outline-primary' type="submit" name="" value="Submit">
  </div>

</form>
</div>
<!-- Footer -->
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
        <a color="#E41F09" class="btn btn-outline-white" href="#" target="_blank" role="button">9860311717 
            <i class="fas fa-phone"></i>
        </a>
        <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">MedicineBook.com
            <i class="fa fa-envelope" aria-hidden="true"></i>
        </a>


    <!--Copyright-->
    <div class="footer-copyright py-3" color="white">
        © 2018 Copyright:
        <a href="https://mail.google.com/mail/u/0/#inbox" target="_blank"> MedicineBook@gmail.com </a>
    </div>
    <!--/.Copyright-->

{% endblock %}

shop_app/templates/shop_app/medicine_confirm_delete.html
{% extends 'shop_app/base.html' %}
{% block sample %}
<br><br>
<div class="jumbotron container mod">
  <h3>Delete {{medicine.Name}} ?</h3>
  <hr>
  <form  method="post">
    {% csrf_token %}
    <input class="btn btn-danger"type="submit"  value="Delete">
    <a href="{% url 'shop_app:StockDetail' pk=medicine.pk %}"> Cancel</a>
  </form>
  <hr>
</div>

{% endblock %}

shop_app/templates/shop_app/medicine_detail.html
{% extends 'shop_app/base.html' %}
{% block sample %}
<div class="wel" >
  <h1>Medicine Detail Page</h1>
  <hr id="ee">
  <h2>Medicine Details  </h2>
</div>

<div class="clasy jumbotron container">

      <h3>Name : {{stock_detail.Name}}</h3>
      <hr>
    <h3>Salt: {{stock_detail.Salt}}</h3>
    <hr>
  <h3>Company : {{stock_detail.Company}}</h3>
  <hr>
  <h3>MRP : {{stock_detail.MRP}}</h3>
  <hr>
  <h3>MFD : {{stock_detail.MFD}}</h3>
  <hr>
  <h3>Expiry : {{stock_detail.Expiry}}</h3>
  <hr>



 <p><a class ="btn btn-warning " href="{% url 'shop_app:update' pk=stock_detail.pk %}">Update</a>  
     <a class ="btn btn-danger " href="{% url 'shop_app:delete' pk=stock_detail.pk %}">Delete</a>  
     <a class ="btn btn-success " href="{% url 'shop_app:addToCart' pk=stock_detail.pk %}"> Add To Cart </a>
 </p>

</div>

{% endblock %}

shop_app/templates/shop_app/medicine_form.html
{% extends 'shop_app/base.html' %}
{% load crispy_forms_tags %}
{% block sample %}
<h1 class="qrt">
  {% if not form.instance.pk %}
  Add New Medicine
  {% else %}
  Update Medicine
  {% endif %}
</h1>
<div class="jumbotron container">
  <form  method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form|crispy }}
    
    <input type="submit" class="btn btn-primary" value="submit">
  </form>
</div>



{% endblock %}
    

shop_app/templates/shop_app/medicine_list.html
{% extends 'shop_app/base.html' %}
{% block sample %}
<div class="soc">
    <h3>Medicines List</h3>
</div>
<div  class="alert alert-info container" role="alert">
  <div class="sb container">
    <form  id="saq" class="form-inline my-2 my-lg-0 " method="get" action="{% url 'shop_app:SearchData' %}">

        <input class="form-control mr-sm-2" type="text" placeholder="Enter Medicine Name" aria-label="Search" name="q">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        <a style="margin-left: 50%;" class ="btn btn-success " href="{% url 'shop_app:myCart' %}"> View Cart </a> 

      </form>
  </div>
</div>

<br>
 <div class="jumbotron container">
   {% for stock in stock_list %}
   <div class="alert alert-dark" role="alert">
     <p><a class=" bad" href="{{stock.id}}">{{stock.Name}}</a></p>
   </div>

  <hr>
  {% endfor %}
 </div>





{% endblock %}

shop_app/templates/shop_app/myCart.html
{% extends 'shop_app/base.html' %}
{% block sample %}
<div class="soc">
    <h3> <center> Medicines List </center> </h3>
</div>

<br>
      <table class="table table-secondary">
        <tr class="table-hover table-secondary">
         <th>Tablet</th>
         <th>Price</th>
         <th>Quantity</th>
       </tr>
       {% for item in items %}
       <tr class="table-hover table-secondary">
         <td>{{item.medicine.Name}}</td>
         <td>{{item.medicine.MRP}}</td>
         <td>{{item.quantity}}</td>
         <td><a class ="btn btn-danger" href="{% url 'shop_app:removeFromCart' pk=item.pk %}"> Delete </a> </td>
         <td><a class ="btn btn-success" href="{% url 'shop_app:checkout' pk=item.pk %}"> Buy </a> </td>
       </tr>
  {% endfor %}
      </table>

{% endblock %}